### ISSUE TITLE
Bot para renogociar itens que estão a 10 dias sem vender depois do escrow

### ISSUE THREAD

**Issue by mageddo** [mageddo/mageddo#10]
Ter items com mais de 10 dias sem vender depois do escrow não é aceitável, dado essa situação deve-se olhar o mercado, olhar o preco que o item foi comprado e abaixar a margem de lucro dado um limite [entender qual seria esse limite e.g. 13%]

- [ ] Buscar os itens que estão a mais de 10 dias depois de vencido o escrow sem vender
- [ ] Procurar o preco da compra desse item
- [ ] Olhar o mercado e ver o quanto dá pra abaixar o preco
- [ ] Re-listar o item
